# Imagen base oficial de Python
FROM python:3.10-slim

# Carpeta de trabajo dentro del contenedor
WORKDIR /app

# Esto copia el archivo app.py dentro del contenedor creado
COPY app.py .

# Con este comando se ejecuta el programa
CMD ["python", "app.py"]
